on: [push, pull_request]

jobs:
  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v3.2.0
        with:
          version: 1.4.8
      - run: nim --version
      - run: nimble test